import type { Metadata } from "next";
import { Manrope } from "next/font/google";
import localFont from "next/font/local";
import Navbar from "./components/Navbar";
import "./globals.css";

const manrope = Manrope({
  subsets: ["latin"],
});

const melodrama = localFont({
  src: "./fonts/Melodrama-Variable.woff2",
  variable: "--font-melodrama",
});

const satoshi = localFont({
  src: "./fonts/Satoshi-Variable.woff2",
  variable: "--font-satoshi",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${manrope.className} ${melodrama.variable} ${satoshi.variable} h-full antialiased`}>
      <body className="min-h-full flex flex-col bg-black">
        <Navbar />
        {children}
      </body>
    </html>
  );
}
